### ISSUE TITLE
OCSP responses for en.wikipedia.org, godaddy.com, and ietf.org (among others) fail to parse

### ISSUE THREAD

**Issue by alanhuang122** [alanhuang122/ocsp-utils#2]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ocsp.py", line 91, in contact_ocsp_server
    response = ocsp.OCSPResponse.load(data.raw.data)
  File "/usr/lib/python2.7/site-packages/asn1crypto/core.py", line 230, in load
    value, _ = _parse_build(encoded_data, spec=spec, spec_params=kwargs, strict=strict)
  File "/usr/lib/python2.7/site-packages/asn1crypto/core.py", line 5099, in _parse_build
    return (_build(*info, spec=spec, spec_params=spec_params), new_pointer)
  File "/usr/lib/python2.7/site-packages/asn1crypto/core.py", line 5008, in _build
    tag
ValueError: Error parsing asn1crypto.ocsp.OCSPResponse - tag should have been 16, but 28 was found
```

**Comment by alanhuang122** [comment]
Fixed with commit 186eb0d.
